name: build
on:
  push:

jobs:
  github_build:
    name: build docker
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build
        run: |
          set -x
          docker compose build rsyslog

      - name: push
        run: |
          TAGKEY=`docker images | grep web  | awk '{print $3}'`
          docker tag "$TAGKEY" ghcr.io/zinntikumugai/rsyslog
          docker push ghcr.io/zinntikumugai/rsyslog

